name = "globalStaffordFormal"
version = "1.0.6"
defaultTargets = ["GlobalStafford", "GlobalStaffordSolution"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "algebraicAnalysis"
git = "https://github.com/itpplasma/algebraic-analysis.git"
rev = "4aae47967f6ba02ffe2f639ab06564c9a9d1ecc8"

[[require]]
name = "stafford38Formal"
git = "https://github.com/itpplasma/stafford38-formal.git"
rev = "e77e176c381ca2d6b20c030f9227f1b031415d2e"

[[lean_lib]]
name = "GlobalStafford"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "GlobalStaffordTest"

[[lean_lib]]
name = "GlobalStaffordChallenge"

[[lean_lib]]
name = "GlobalStaffordSolution"
